### ISSUE TITLE
Tree Shakeable Injector

### ISSUE THREAD

**Issue by garand** [Anidetrix/rollup-plugin-styles#122]
Hey! Love the project, working great for me. However I'd like to be able to tree-shake my styles with my components. For instance, if I had 10 components, all 10 groups of styles would be injected even if only 3 components are used on a page.

I like the approach [here](https://github.com/dferber90/rollup-plugin-postcss-treeshakeable) where  

```jsx
<div className={style.myThing} />
```

Becomes

```jsx
<div className={style().myThing} />
```

Out of the box that package doesn't work with rollup-plugin-styles. I'm trying to experiment with a custom injector to do it, but no luck just yet.

Is this something you'd consider adding as a built in option?

**Comment by Anidetrix** [comment]
Hi @garand,

At the time, object treeshaking is not yet supported by rollup (see [here](https://github.com/rollup/rollup/issues/2201)), but there are alternative solutions for this:

1.  Use [named exports](https://anidetrix.github.io/rollup-plugin-styles/interfaces/_index_d_.options.html#namedexports)
or
2. Use [rollup-plugin-terser](https://www.npmjs.com/package/rollup-plugin-terser)

Hope it helps!

**Comment by Anidetrix** [comment]
Looking through the provided plugin again, I think I now understand what this accomplishes. By the way, it is not connected to injector, but to generated embedding code. Shouldn't be too hard to implement actually, so I'll try.

**Comment by Anidetrix** [comment]
Hi again @garand,

This feature is available now, in version 3.10.0! To enable it use `treeshakeable` option:

```js
styles({ mode: ["inject", {treeshakeable: true}] })
```

I gave myself a week to come up with something better, but in the end getter-based approach seems like the best compromise for now. Also, to inject global styles without using any classes, use it like so:

```js
import styles from "./style.css"
styles.inject()
```

Let me know if that is works for you!

**Comment by garand** [comment]
@Anidetrix This is awesome! I'll try it out right now. Do I need to run `.inject()` or can I call it like I referenced in the initial issue comment?

**Comment by Anidetrix** [comment]
@garand Use `.inject()` only if you don't use any classes from the file and you still want it to be injected.

If you use any class, like so:

```js
import styles from "./style.css"
console.log(styles.anyClassName)
```

CSS will be injected automatically.

**Comment by garand** [comment]
Great! I don't see 3.10.0 yet, is that still being deployed?

Also... all of a sudden I am getting this error recently:

```
[!] (plugin styles) Error: Unable to load PostCSS plugin `0`
```

Not sure what would be causing it. This is my postcss.config.js. That config is working fine in other projects and all of the dependencies are installed.

```js
module.exports = {
  plugins: [
    require('postcss-import'),
    require('postcss-edgie'),
    require('tailwindcss'),
    require('postcss-preset-env')({ stage: 0 }),
    require('autoprefixer'),
  ],
}
```

I can create a separate issue if needed.

**Comment by Anidetrix** [comment]
> Great! I don't see 3.10.0 yet, is that still being deployed?

Yes

> [!] (plugin styles) Error: Unable to load PostCSS plugin `0`

This was also fixed in 3.10.0

**Comment by Anidetrix** [comment]
3.10.0 is up if you haven't seen yet, hope this is what you were looking for!

**Comment by garand** [comment]
Already installed and trying it now. I'll let you know if it's doing what I expect!

**Comment by garand** [comment]
Seems to be working just great so far. Will make additional issues later if I discover any functionality that is missing. Thanks for the hard work. 🙌

**Comment by garand** [comment]
@Anidetrix For that PostCSS plugin issue... it came up again, I cleared out `node_modules`, installed again, and then it built fine... Any ideas? Seems to come up periodically.

**Comment by Anidetrix** [comment]
@garand I believe this should not be the case since code for that isn't particularly complex, probably package manager just messed up. But if the issue will appear on a regular basis I can investigate more thoroughly.

**Comment by garand** [comment]
Okay, sounds good. I'll let you know if it keeps coming up. Appreciate the quick responses!
