### ISSUE TITLE
mode extract missing files

### ISSUE THREAD

**Issue by atompkins** [Anidetrix/rollup-plugin-styles#124]
So my use case is that I want all of the css to be bundled into a single file. Is this supported?
The closest I have got so far is to use mode: ['extract', 'filename.css']
Even though I have provided the output filename it still respects assetFileNames so I changed this to '[name][extname]'
Luckily I don't have any other assets so this isn't causing an issue.

Whenever I provide a filename for the extract output I loose files. The missing ones tend to be top level imports, code split modules seems to come through OK.

Default mode injection works fine, I just don't want my js bloated with css.
Extract without a filename seems to work OK, just lots of files.

**Comment by Anidetrix** [comment]
Hi @atompkins,

I think I'll need a reproduction repo for that. Can you make one using rollup's REPL, REPL.it, or just GitHub repo?

**Comment by atompkins** [comment]
I think this shows the problem: https://repl.it/@PointyHair/rollup-repro

**Comment by Anidetrix** [comment]
Hmm, seems like a bug indeed, going to fix that and let you know.

**Comment by Anidetrix** [comment]
Hi again @atompkins,

Seems like I fixed it, fix is included in the 3.10.0 release.

Let me know if it works for you!

**Comment by atompkins** [comment]
Yes it does, thank you :)
