### ISSUE TITLE
less options. provided `paths` do not work.

### ISSUE THREAD

**Issue by argesoft** [Anidetrix/rollup-plugin-styles#125]
When I provide `paths` in the less loader options, loader does not take it into account (or does not receive it).
Other parameters of options work as expected, but `paths` somehow does not.
When I import file only by its name (as it can be located in different folders depending on config) less loader does not scan provided paths and returns error `(plugin styles) Error: Cannot find module './config.less' from '--__dirname--\src\'`.

To reproduce:

package.json
~~~json
{
  "devDependencies": {
    "less": "^3.11.3",
    "rollup": "^2.18.1",
    "rollup-plugin-styles": "^3.10.0"
  }
}
~~~

rollup.config.js
~~~js
const styles = require("rollup-plugin-styles");

module.exports = {
    input: "./src/index.less",
    plugins: [
        styles({
            less: {
                paths: [
                    "./src/config",
                    `${__dirname}/src/config`
                ]
            }
        })
    ]
}
~~~

./src/index.less
~~~less
@import "config.less";

.test {
    color:black;
}
~~~

./src/config/config.less
~~~less
.test {
    color:red;
}
~~~
The same scenario works for other less plugins.
Am I doing something wrong?

Tested on windows 10, node v12.18.1

**Comment by argesoft** [comment]
Maybe this explains better
https://repl.it/@argesoft/rollup-styles-test

**Comment by Anidetrix** [comment]
Hi @argesoft, sorry for the late response.

I believe the issue is that since the plugin uses custom Less importer paths are not respected properly, will fix that and let you know!

**Comment by argesoft** [comment]
Thank you @Anidetrix 
Yes, the problem is related with custom importer.
I've commented line 32 in [the importer source](https://github.com/Anidetrix/rollup-plugin-styles/blob/master/src/loaders/less/importer.ts) and the issue resolved.
But now I found a different problem.
~~~css
@font-face {
	font-family: 'PT Sans';
	font-style: normal;
	font-weight: 400;
--->>	src: local('PT Sans'), local('PTSans-Regular'),  url('fonts/PTS-webfont.woff') format('woff');
}
~~~
When there is a `src` attribute mixed with `local`, then `url` is not processed at all.
Even `url->resolve` option does not see it.

**Comment by kaiyoma** [comment]
I just ran into this today and it would be nice to have this working so I don't have lots of `../../../`-style imports in my code. Can we get a fix please?

**Comment by StreetStrider** [comment]
@Anidetrix, Hello.
I can't find comprehensive description of how certain loaders (first, less in my case) are configured. The readme says that they just work. What if I need to provide custom vars to less or configure it in any other way? Same for other loaders.

Btw, the api reference link in the readme is broken. I've located less part manually, but it seemes to be autogenerated stub.

**Comment by StreetStrider** [comment]
I've consulted `types.ts` for all required information.
