### ISSUE TITLE
postcss issue. not resolving `url` in `src` mixed with `local` attribute

### ISSUE THREAD

**Issue by argesoft** [Anidetrix/rollup-plugin-styles#126]
As I mentioned [here](https://github.com/Anidetrix/rollup-plugin-styles/issues/125#issuecomment-653124822) there is an issue in processing compiled css.
When there is a code with a line like below, postcss does not process it
~~~css
@font-face {
	font-family: 'PT Sans';
	font-style: normal;
	font-weight: 400;
--->>	src: local('PT Sans'), local('PTSans-Regular'),  url('fonts/PTS-webfont.woff') format('woff');
}
~~~
When there is a `src` attribute mixed with `local`, then `url` is not processed at all.
Even `url->resolve` option does not see it.

_Originally posted by @argesoft in https://github.com/Anidetrix/rollup-plugin-styles/issues/125#issuecomment-653124822_

**Comment by argesoft** [comment]
As far as I can see, the issue is related to `url` resolver. [source](src/loaders/postcss/url/utils.ts) lines 7-8
After replacing `/^(?:url|(?:-webkit-)?image-set)\(/i` with `/^(?:[a-z]{3,}|(?:-webkit-)?image-set)\(/i` it works as expected
Is there a better solution?

**Comment by Anidetrix** [comment]
Hi again @argesoft,

Hmm, well this is peculiar. Will investigate this and let you know.

**Comment by olemartinorg** [comment]
This had me stumped for too long. Fixing the regex by removing the `^` (to let it look past just the start) also works for me. It's pretty obvious (as in the example) that the value does not always start with `url(` when it contains a `url(`. Hoping for a quick fix for this!
