### ISSUE TITLE
Css modules styles order is not consistent

### ISSUE THREAD

**Issue by vladshcherbin** [Anidetrix/rollup-plugin-styles#134]
Same as https://github.com/egoist/rollup-plugin-postcss/issues/96

When using css modules and compiling to a single css file, the order of compiled styles doesn't stay the same. This breaks flow when you have `reset.css` styles and some deep component styles are placed before it.

**Comment by Anidetrix** [comment]
Hello @vladshcherbin,

Can you confirm order is wrong? Can you make minimal reproduction repo using [rollup's REPL](https://rollupjs.org/repl/), [REPL.it](https://repl.it/@rollup/rollup-repro), or just GitHub?

**Comment by vladshcherbin** [comment]
I believe I can't, created a repo and can't reproduce it. Probably messed somewhere locally while testing lots of plugins. I'll reopen if will see again, sorry.
