### ISSUE TITLE
Prevent extraction and injection

### ISSUE THREAD

**Issue by geotrev** [Anidetrix/rollup-plugin-styles#137]
Hi there. 

I have a use-case where I need to inject my styles into the final JS bundle. Is that possible? I don't see an option to do that from the docs, but maybe I missed it.

Thanks!

**Comment by Anidetrix** [comment]
Hi @geotrev,

I guess you figured it considering you closed the issue, but just in case - this is the default behavior, as it is mentioned in the Usage section in the README, and also in the [`mode` option description in the API Reference](https://anidetrix.github.io/rollup-plugin-styles/interfaces/_index_d_.options.html#mode)
