### ISSUE TITLE
Unresolved URL error when query string or hash in url

### ISSUE THREAD

**Issue by adieu** [Anidetrix/rollup-plugin-styles#138]
We cannot handle url with query string or hash right now.

For example:

```
url("../assets/fonts/icons.svg#icons")
```

`Unresolved URL` error will be raised because we are trying to resolve the full url instead of the `pathname` part.

We can walk around this issue by setting a custom `resolve` func but the query string and hash parts will be removed in the final url.

**Comment by matthew-dean** [comment]
Same issue. I want to rewrite the URL but preserve the hash / querystring.

**Comment by rchl** [comment]
Likely resolved by https://github.com/Anidetrix/rollup-plugin-styles/pull/148.

**Comment by Anidetrix** [comment]
Fixed
