### ISSUE TITLE
warning about google fonts

### ISSUE THREAD

**Issue by mnlbox** [Anidetrix/rollup-plugin-styles#140]
Hi @Anidetrix ,
I got this error on my build process:
```
(!) Plugin styles: Unresolved `@import` in `@import url("https://fonts.googleapis.com/css?family=Gudea:400,700")`
```

I used google font in some of my `scss` files. Do I need to set any options to solve this?

**Comment by rchl** [comment]
Maybe try with `import: false` option.

**Comment by mnlbox** [comment]
@rchl No, it does not fix the problem
