### ISSUE TITLE
Inject var instead of const?

### ISSUE THREAD

**Issue by mindplay-dk** [Anidetrix/rollup-plugin-styles#145]
I have the plugin configured like this:

```
        styles({
            // https://anidetrix.github.io/rollup-plugin-styles/interfaces/_index_d_.options.html
            mode: ["inject", () => ""], // NOTE: using an empty closure to bypass code-generation in `styles` and just inline the CSS source
            minimize: true,
        }),
```

(Note that I'm using a custom callback with `inject` here to bypass the built-in code generation - I just want the CSS as a string, I have my own code for injecting it.)

Now the input:

    import css from "./widget.css";

Correctly gets converted to:

    const css = "....";

And so far so good.

But then *after* your plugin, I have the Babel plugin, which is configured to convert `const` into `var`.

Somehow that doesn't work?

Other `const` in my code get converted to `var` - but the resulting `const` from this plugin does not.

Changing the order of plugins doesn't seem to change anything.

Is there any way to configure the plugin itself to emit `var` instead of `const`?

(Doesn't the plugin order in rollup define the order of processing? or what am I not understanding here?)

**Comment by Anidetrix** [comment]
Hello @mindplay-dk,

I believe this has been fixed by @tjenkinson in his Pull Request, but it has not been released yet. I did not have a lot on time to work on this plugin lately, but this should be fixed in the next release.

**Comment by mindplay-dk** [comment]
Looks like [yes](https://github.com/Anidetrix/rollup-plugin-styles/pull/129/files).

If you want to publish a pre-release, I'd be happy to test. 🙂

**Comment by Anidetrix** [comment]
Should be fixed for a while, closing
