### ISSUE TITLE
a way to embed already processed files into js file

### ISSUE THREAD

**Issue by jd1378** [Anidetrix/rollup-plugin-styles#174]
I'm using [vite](https://vitejs.dev/) and im trying to build a single file from my project, but anything I have tried creates an external css file.
I found your plugin for rollup and tried to use it , but it says `[plugin:styles] Skipping processed file ....` and it doesn't end up in my js file.
I wanted to know if it's possible to force it to embed the css into js file using your plugin ?

**Comment by jd1378** [comment]
apparantly using `build.lib` config of vite does the embedding, so this plugin was not needed.

**Comment by RossComputerGuy** [comment]
Is there a solution for non-vite setups?

**Comment by jd1378** [comment]
i haven't do any search, but from what I remember the plugin didn't have such option.
maybe search on your setup
