### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by diego-antonelli** [Anidetrix/rollup-plugin-styles#196]
Hi, can those 2 vulnerable libraries be bumped? Both libraries are being used in some other dependencies and snyk complains a lot about.

https://snyk.io/advisor/npm-package/rollup-plugin-styles

**Comment by diego-antonelli** [comment]
* Note, its just `cssnano` that needs to be upgraded to v5.0.0

**Comment by diego-antonelli** [comment]
Master apparently is already using v5 of cssnano, can you bump the version and release a new package through npmjs?

**Comment by Anidetrix** [comment]
@diego-antonelli I'll be releasing the new version in the upcoming week or two, have a few hardware issues at the moment.

**Comment by diego-antonelli** [comment]
Thats perfect. Thanks a lot!

**Comment by diego-antonelli** [comment]
> @diego-antonelli I'll be releasing the new version this, or maybe next week, have a few hardware issues at the moment.

Any updates?

**Comment by ghost91-** [comment]
Any news by now?

**Comment by diego-antonelli** [comment]
@ghost91- I gave up of waiting and implemented postcss instead, which gave me the same defaults.

**Comment by o-mega** [comment]
@diego-antonelli can you show your implementation of postcss instead of this plugin?

**Comment by diego-antonelli** [comment]
@o-mega https://github.com/mendix/widgets-resources/pull/1078/commits/19fe675543ff8e5e1bfb6ceb6963e6e4d057ba6f

**Comment by o-mega** [comment]
@diego-antonelli thank you a lot! You saved my day!

**Comment by diego-antonelli** [comment]
You're welcome @o-mega. I will close the issue as nobody is taking actions and I solved my problem.
